language: cpp
sudo: required
dist: bionic
install:
    - choco install python
    - RefreshEnv
    - choco install pip
    - choco install ninja
    - pip3 install meson
    - choco install make
    - meson --buildtype release build
    #- make get-deps
notifications:
    email: false
compiler:
    - gcc
    - clang
os:
    #- linux
    #- osx
    - windows

script:
    - ./configure
    - make
    - make check
    - sudo make install
    - make check-install
    - sudo make uninstall
